[book]
authors = ["Ethereum"]
language = "en"
multilingual = false
src = "src"
title = "Ethereum stateless book"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
smart-punctuation = true
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/stateless-consensus/eth-stateless-book"
edit-url-template = "https://github.com/stateless-consensus/eth-stateless-book/edit/main/{path}"

[output.html.fold]
enable = true
level = 0
